# Generated by Django 5.1.1 on 2024-09-22 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("psychometric", "Psychometric"),
                            ("aptitude", "Aptitude"),
                            ("reasoning", "Reasoning"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        choices=[
                            ("o_score", "O Score"),
                            ("c_score", "C Score"),
                            ("e_score", "E Score"),
                            ("a_score", "A Score"),
                            ("n_score", "N Score"),
                            ("numerical", "Numerical"),
                            ("verbal", "Verbal"),
                            ("logical", "Logical"),
                        ],
                        max_length=255,
                    ),
                ),
                ("option_1", models.CharField(max_length=255)),
                ("option_2", models.CharField(max_length=255)),
                ("option_3", models.CharField(max_length=255)),
                ("option_4", models.CharField(max_length=255)),
                ("correct_option", models.CharField(max_length=255)),
                ("option_1_score", models.IntegerField(default=0)),
                ("option_2_score", models.IntegerField(default=0)),
                ("option_3_score", models.IntegerField(default=0)),
                ("option_4_score", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("o_score", models.FloatField(default=0)),
                ("c_score", models.FloatField(default=0)),
                ("e_score", models.FloatField(default=0)),
                ("a_score", models.FloatField(default=0)),
                ("n_score", models.FloatField(default=0)),
                ("numerical_ability", models.FloatField(default=0)),
                ("verbal_reasoning", models.FloatField(default=0)),
                ("logical_reasoning", models.FloatField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
