# Generated by Django 5.1.4 on 2025-01-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Assessment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RIASEC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("R", "Realistic"),
                            ("I", "Investigative"),
                            ("A", "Artistic"),
                            ("S", "Social"),
                            ("E", "Enterprising"),
                            ("C", "Conventional"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "response_value",
                    models.IntegerField(
                        choices=[
                            (1, "Strongly Disagree"),
                            (2, "Disagree"),
                            (3, "Neutral"),
                            (4, "Agree"),
                            (5, "Strongly Agree"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="A_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="C_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="E_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="I_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="R_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="S_score",
            field=models.FloatField(default=0),
        ),
    ]
