# Generated by Django 5.1.4 on 2025-01-27 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Assessment", "0002_riasec_userprofile_a_score_userprofile_c_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="A_score",
            new_name="AR_score",
        ),
    ]
