# Generated by Django 5.1.4 on 2025-01-27 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Assessment", "0003_rename_a_score_userprofile_ar_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="C_score",
            new_name="CR_score",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="E_score",
            new_name="ER_score",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="I_score",
            new_name="IR_score",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="R_score",
            new_name="RR_score",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="S_score",
            new_name="SR_score",
        ),
    ]
