# Generated by Django 5.1.4 on 2025-01-27 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Assessment", "0005_remove_userprofile_ar_score_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RIASEC",
        ),
    ]
