# Generated by Django 5.1.1 on 2024-09-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="career_images/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="branch_images/")),
                ("description", models.TextField()),
                ("video", models.FileField(upload_to="branch_videos/")),
                (
                    "career_path_image",
                    models.ImageField(upload_to="career_path_images/"),
                ),
                ("opportunities", models.TextField()),
                ("average_salary", models.CharField(max_length=100)),
                ("pros", models.TextField()),
                ("cons", models.TextField()),
                (
                    "career_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="careerlibrary.careeroption",
                    ),
                ),
            ],
        ),
    ]
