# Generated by Django 5.1.4 on 2025-05-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careerlibrary", "0002_careeroption_stream_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careeroption",
            name="stream_type",
            field=models.CharField(
                choices=[
                    ("Science", "Science"),
                    ("Commerce", "Commerce"),
                    ("Arts", "Arts"),
                ],
                default="Science",
                max_length=50,
            ),
        ),
    ]
