# Generated by Django 5.1.4 on 2025-05-10 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("level1", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mlpredictionresult",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="mlpredictionresult",
            name="prediction_data",
        ),
        migrations.RemoveField(
            model_name="mlpredictionresult",
            name="recommendation",
        ),
        migrations.AddField(
            model_name="mlpredictionresult",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mlpredictionresult",
            name="growth_areas",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="mlpredictionresult",
            name="key_strengths",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="mlpredictionresult",
            name="radar_scores",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="mlpredictionresult",
            name="predicted_personality",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mlpredictionresult",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
